name: pythonworkflow
on: workflow_dispatch

jobs:
        data_pipeline:
                name: data_pipeline
                runs-on: ubuntu-latest
       
                steps:
                - name: setup python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.10"

                - name: checkout code
                  uses: actions/checkout@v4

                - name: install dependencies
                  run:
                    cd ModelCleaning
                    pip install -r requirements.txt

                - name: clean_data
                  run: |
                    pwd
                    ls -al
                    pwd
                    cd ModelCleaning
                    python Cleandata.py

                - name: train_test model
                  run: |
                    pwd
                    cd ModelCleaning 
                    python train_test_dataset.py
                    ls -al
