name: tutorial1
on: push

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: |
            echo "Hello from job1"
            date
    
    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - name: step2
          run: |
            echo "Hello from job2"
            Get-Date

    job3:
        runs-on: ubuntu-latest
        steps:
        - name: step3
          run: |
            echo "Hello from job3"
            date

    job4:
        runs-on: ubuntu-latest
        steps:
        - name: step4
          run: |
            echo "Hello from job3"
            date